### PR TITLE
Improved Ride the Currents to update the UI as soon as the card is moved

### LINKED ISSUE #608: Superstorm - Ride the Currents, display bug
**Describe the bug**
When moving an environment card at the start of the villain turn, the card move is not visually displayed until the UI switches to the hero turns (presumably when it forces an update of some sort)

**What does it affect**
Card(s): Ride the Currents
Deck(s): Superstorm

**To Reproduce**
1. Superstorm Akela has multiple cards in play, including Ride the Currents
2. At the start of the villain turn, specify a new position for one of the environment cards
3. See no change in the displayed environment play area
4. After the UI switches panel positions to a hero turn, see the environment cards are now in the modified order

**Expected behavior**
The order change is visible immediately.

**Screenshots**

**Logs**

**Additional context**

### PR DESCRIPTION
**Pull request by wrhyme29**
Closes #608

### CODE REVIEW

**Comment by wrhyme29** [comment]
I accomplish this by adding 2 flip card actions after the movement of the cards. These Flip card actions force the UI to update. However, since these FlipCardActions aren't really happening, we flag them as being unable to be responded to and unable to be cancelled. 

There will still be journal entries saying that the card flips to its backside and flips to its front, but i don't think thats too big of a deal, as most people won't be looking at the logs.

**Comment by LNBertolini** [comment]
This resets the HP of any targets flipped this way.

**Comment by wrhyme29** [comment]
Good point - a simple storage of HP and setting HP after should be sufficient there, especially if we mark the setting of HP as non respondable by triggers

**Comment by wrhyme29** [comment]
I know its visually obvious, but I don't have a problem with it. It sort of just feels like a moving animation to me.

**Comment by wrhyme29** [comment]
Can you take another look at this - it should take card of the issue

**Review by LNBertolini — APPROVED** [review]

**Pull request merged**
