### PR TITLE
Use a conditional Trigger for the damage prevention incap

### PR DESCRIPTION
**Pull request by qoala**
It needs to be able to block execution  when the player is choosing ambiguous lowest HP with AllowFastCoroutinesDuringPretend=false or similar, and that doesn't seem possible with status effects.
This is based on the proposed fix for Element of Lightning, though I clear the card property by defining a trigger on `ExpireStatusEffectAction`, so that it expires on status effect timing (status effects expire before normal "start of turn" triggers).

Also fix it ignoring damage from non-target sources (which should still be prevented if the "to the target with the lowest HP" side is triggered).

### CODE REVIEW

**Review by Vilnor — COMMENTED** [review]
These triggers will be active and checked while TangoOne is alive.  This criteria should check she is Incapacitated before proceeding.
AddSideTrigger exists on hero's and can be used to Add a trigger once TangoOne flips much like a villain.
lastly, methods exist to revive flipped Heroes. This didn't matter before, but might matter with this implementation.

**Comment by Vilnor** [comment]
On further pondering, I think my concerns are unfounded.

**Comment by qoala** [comment]
It's worth adding a test to make sure it works around revival. (Revival should not cancel the incap affe5ct)

I used outOfPlay trigger so that flipping didn't remove the trigger, but didn't check that everything is fine with flipping back.

**Comment by qoala** [comment]
Updated to use SideTriggers.

Tested incap behavior around revival in vanilla with Best of Times Chrono Ranger. Apparently revival immediately ends StatusEffect-based effects generated by the character card, so the effect ends and never needs to listen on the front side.
A new test also verifies that the `Trigger<ExpireStatusEffectAction>` correctly clears the property upon revival, so that it doesn't reinstate itself if she's incapped again later.

**Pull request merged**
