### PR TITLE
Mythos Subdecks

### PR DESCRIPTION
**Pull request by wrhyme29**

### CODE REVIEW

**Comment by wrhyme29** [comment]
Challenges to solve:

The Mythos subdeck stuff is probably going to break him until there's been some finagling him to let his subdeck cards fake being normal deck cards
(starting in the right place, going to standard trash rather than subtrash, finessing anything that cares about Card.NativeDeck...)

**Comment by origamiswami** [comment]
I updated this branch with some things I found out while coding Glyph. It should work fine with any cards that manipulate decks now. As part of the updates, I also changed all instances of `card.NativeDeck` to `GetNativeDeck(card)` instead, since that allows the card itself to override the native deck (e.g. mission cards).

**Comment by wrhyme29** [comment]
I've rebased off of main, collapsed commits down, and update the arts to use the new ones @angi11e made

**Review by wrhyme29 — COMMENTED** [review]
Tested in game, looks good

**Review by origamiswami — APPROVED** [review]

**Pull request merged**
