### PR TITLE
Mythos Peer Review

### PR DESCRIPTION
**Pull request by mgirman520**

### CODE REVIEW

**Comment by MSpekkio** [comment]
Icon Order is incorrect. I believe this is show the bottom of the deck up.  Note Madness, Danger, Madness.
image
Play a card
image

Still Madness, Danger, Madness
image

**Comment by MSpekkio** [comment]
Dangerous Investigation prompt uses wrong action;
image

**Comment by MSpekkio** [comment]
"This card has a blue circle icon"?
image

**Comment by wrhyme29** [comment]
> Icon Order is incorrect. I believe this is show the bottom of the deck up. Note Madness, Danger, Madness.
> image
> Play a card
> image
> 
> Still Madness, Danger, Madness
> image

As an FYI - this is a a thing generally - the list of cards in the a location's cards list is the opposite of the card order. If you look at  the TopCard property, it pulls from the back of the array

**Comment by mgirman520** [comment]
Decklist is reversed, I went with Blue Clue, Red Danger, Green Madness as this is the color and the official name of the icon. As the icons are currently not visible anywhere in the deck leaving both will help until we can put icons in.

**Review by wrhyme29 — APPROVED** [review]

**Pull request merged**
