### PR TITLE
Gyrosaur Peer Review

### PR DESCRIPTION
**Pull request by LNBertolini**

### CODE REVIEW

**Comment by MSpekkio** [comment]
FYI, did a full game with Gyrosaur, didn't encounter anything to screen shot and report.  Game play wise (on the cards I hit obviously) looked great.

**Comment by LNBertolini** [comment]
Re: "Corrected Sphere of Devastation damage"

Nope! Read the card again - X is four times the number of crash cards discarded, but the card does X**+4** damage.

**Comment by NinjaMonkey1234** [comment]
Not sure how I completely missed the extra 4. Was focused on finding where the +1 had come from. The formula makes sense.

**Review by NinjaMonkey1234 — APPROVED** [review]
Everything looks good.

**Pull request merged**
