### PR TITLE
Terminus - Complete Deck and Variants

### PR DESCRIPTION
**Pull request by NinjaMonkey1234**
Ready for peer review

### CODE REVIEW

**Comment by MSpekkio** [comment]
The Base Character Card controller needs an implementation of ShouldBeDestroyedNow() to return true when Terminus's Stain Badge's indestructibility drops.

Obliveon Mode needs a special case of all visible Turn Taker's Hero's are incapacitated.

Stained Badge needs more tests.  Representative of Earth, Resurection Ritual, TheSentinels partial incap'd comes to mind. Basics like the Game Ends with a Hero Defeat victory.  I suspect there's some edge cases with behavior when Terminus's HP is negative that need to be checked.

**Comment by NinjaMonkey1234** [comment]
I've moved all indestructible logic into Stained Badge. Terminus will now incap if she has 0 or less HP and there are no other non-incapped heroes she can see due to battle zone or something like Isolated Hero.

I'll work on getting some additional tests in tonight.

**Comment by NinjaMonkey1234** [comment]
I just went back to take a look of the wording on Stained Badge. "**This card and {Terminus} are indestructible.** If another Memento would enter play, instead remove it from the game. **If all other heroes are incapacitated, the heroes lose.**"

The first sentence is telling me that the badge and Terminus are unconditionally indestructible regardless of the state of any other hero or villain. Meaning there should never be a condition short of end of game that could remove the badge or Terminus. 

The last sentence is adding a new lose game condition. The way I read it is that the heroes lose even if Terminus is at full health but every other hero is incapacitated. 

Am I reading the card wrong?

**Comment by MSpekkio** [comment]
> 
> Am I reading the card wrong?

The Decklist text is wrong, the card images on google drive are the source of truth.

image

I did a quick review of all the cards against the drive and only Stained Badge had erroneous text, and I pushed the fix.  I specifically remember the arguments around that original text over of BGG since, yeah, it would do weird things.

**Review by LNBertolini — APPROVED** [review]

**Pull request merged**
