### PR TITLE
Drift Peer Review!!

### PR DESCRIPTION
**Pull request by mgirman520**

### CODE REVIEW

**Comment by MSpekkio** [comment]
Doing a test game, so this is just general feedback.
image
The 'Drift' text everywhere makes things really hard to read.  Since we don't know how long it will be till we get custom icons, I think we should change that text to be as readable as possible in the current implementation.

These are tough to read:
image
image

For the L,LL,LLL's does a <,<<,<<< work?  That would help with readablity.

Art will help, but I think we should change the card title here (which won't effect the code) to Shift Track: Past, Shift Track : Future
image

Issue: I can choose the Past power even though I'm in the future.
This may be a engine limitation, but we may be able to work around it with the GrantedPower stuff
image

If I choose the past power, it still fires the future power.
image

**Comment by MSpekkio** [comment]
Knight's Heritage's shift should be optional
image

When Knight's Heriteage Shift doesn't move you on the track, it consumes the 'first shift this turn' flag.  Past Focus below, only consumes the 'first shift this turn' if the shift actually moves you.

Past Focus's optional shift uses a different UI.  The UI should use the same function with a skip option as the other shift cards.
image
In this case, I was max Future, so I can neither shift right or trigger the effect.

**Comment by MSpekkio** [comment]
Drift character card and the Shift Track cards should have the 'Track Position' special string for consistancy.

**Comment by MSpekkio** [comment]
Destroyer's Adigo
I have no Ongoing Cards in my Trash, first option should be concealed.
image

**Comment by MSpekkio** [comment]
Throwing Shard.
Using the Past Power, trigger's into the Future Power.  I'm not reading the code, but I can see the misplaced If statement.

**Comment by MSpekkio** [comment]
When selecting Character Cards, the Shift Track is  a choice for some effects.  Here it's Cypher's Move an Augment.
image

Some combination of IsReal = false, and Invisibility cloak is required.

**Comment by MSpekkio** [comment]
General note, when possible Shift prompts should put the current Shift Track card as the Associated Card.

**Comment by wrhyme29** [comment]
> For the L,LL,LLL's does a <,<<,<<< work? That would help with readablity.

It looks like < and > are not in the font included with the game, as the game fails to render them at all.

**Comment by MSpekkio** [comment]
> 
> 
> > For the L,LL,LLL's does a <,<<,<<< work? That would help with readablity.
> 
> It looks like < and > are not in the font included with the game, as the game fails to render them at all.

Curses!

**Review by wrhyme29 — APPROVED** [review]

**Pull request merged**
