### PR TITLE
The chasm of a thousand nights Peer review

### PR DESCRIPTION
**Pull request by wrhyme29**

### CODE REVIEW

**Comment by MSpekkio** [comment]
Opinion, with the current implementation there's almost no way to see the art and text on the Nature cards.  Since the Nature play is already worded as a 'random card' I think we should have the cards under Chasm be face up so the players can inspect the cards.

**Comment by MSpekkio** [comment]
I also think we should just snip the setup text from Chasm, and fill in a flavor quote.

**Comment by wrhyme29** [comment]
> Opinion, with the current implementation there's almost no way to see the art and text on the Nature cards. Since the Nature play is already worded as a 'random card' I think we should have the cards under Chasm be face up so the players can inspect the cards.

Thats definitely fair. I'm good with that change.

**Comment by wrhyme29** [comment]
> I also think we should just snip the setup text from Chasm, and fill in a flavor quote.

I can get behind cutting the setup text, especially since it doesn't involve the player at all. There might be some confusion around that to a total newbie though is my only thought.

Flavor text is a great idea - lets throw a line to tosx for that

**Comment by MSpekkio** [comment]
We've also got the wrong art (my fault) for the instruction card.  I assumed it would be a character card, but that doesn't work in environment land.

**Comment by wrhyme29** [comment]
I actually disagree about on play effect SpecialStrings. I use SpecialStrings while cards are in the deck to potentially see whats coming up. On those special strings, I always (or at least have been trying to) add the condition of not in play.

**Comment by MSpekkio** [comment]
> 
> 
> I actually disagree about on play effect SpecialStrings. I use SpecialStrings while cards are in the deck to potentially see whats coming up and what they would hit if they did. They also become relevant if things reveal/play the top cards of the environment deck/ or play things from trash. On those special strings, I always (or at least have been trying to) add the condition of not in play.

Fair, and looking at Baron Blade for example, if does have a similar string.  I'll add it back in.
image

**Comment by MSpekkio** [comment]
I took some liberties with the Setup text to boil it down and fix in the text box.
image

Cards under:
image

**Comment by wrhyme29** [comment]
> I took some liberties with the Setup text to boil it down and fix in the text box.

I think that looks great. Nice work. 

Can you change invisibility to use the undercards not in play override? I meant to but didn't get around to it

**Comment by MSpekkio** [comment]
> Can you change invisibility to use the undercards not in play override? I meant to but didn't get around to it

Not familiar with that,  I'll get out of here in a moment and let you make the change.

**Comment by wrhyme29** [comment]
> Not familiar with that, I'll get out of here in a moment and let you make the change.
I'm not by computer so I won't be able to do it now. I'll just do a chasm cleanup branch like i did for menagerie with it. proceed with your review without it

**Comment by LNBertolini** [comment]
One thing to be wary of is that whether a card is *indestructible* is a bit different from whether that card *can be destroyed*. Make sure the cleanup you did on that doesn't allow something like Freedom Five Legacy's power to get rid of a Nature.

**Comment by MSpekkio** [comment]
> 
> 
> One thing to be wary of is that whether a card is _indestructible_ is a bit different from whether that card _can be destroyed_. Make sure the cleanup you did on that doesn't allow something like Freedom Five Legacy's power to get rid of a Nature.

Thank you QuagaBlast, you are correct, FF Legacies move does still work.  Either re add the MakesIndestructible list or see if a different combination of flags does the thing.

**Review by MSpekkio — APPROVED** [review]

**Review by MSpekkio — APPROVED** [review]

**Pull request merged**
