### PR TITLE
MOSS LotW Revamp

### PR DESCRIPTION
**Pull request by wrhyme29**
Reordered TokenPools so the ElementPool is visible
Refactored many parts of code
Made safe for Guise to copy power
Made safe for Completionist Guise to steal power
Made safe for no double stacking of status effect when another hero uses the power twice

Note: There is still an issue in game UI where after a reload, the AllowFastCoroutinesDuringPretend gets ignored and the decision doesn't actually get paid any attention to. I have a test in the suite but that passes without issues.

### CODE REVIEW

**Comment by wrhyme29** [comment]
From Mspekkio:

"My other thought that I don't want you to chase, is most of the common status effects make a trigger to actually do the effect.  could the created trigger need a isActionConditional, and is there someway to premake that trigger or effect it's constuction.  Possible none of this applies since you are already in a Reflection Status Effect."

**Comment by MSpekkio** [comment]
I looked further into the Trigger creation, and we don't have a way to effect the created trigger.  If this becomes a bigger problem in the future potentially just using a status effect for the text effect, and directly adding the correct trigger to the target character might be an option.

I removed the TurnTaker controller and moved the Token Pool Reorder to MOSS LOTW's constructor as a extension method.  This should be safer across reloads and weirdness.

**Review by wrhyme29 — COMMENTED** [review]
Should this be if targetIndex > 0 not targetIndex > 1?

**Comment by MSpekkio** [comment]
> 
> 
> Should this be if targetIndex > 0 not targetIndex > 1?

yes, thank you.

**Review by MSpekkio — APPROVED** [review]

**Pull request merged**
